version: '3.8'

services:
  nginx:
    container_name: nginx_${PROJECT_NAME}
    build: ./docker/nginx
    environment: 
      PHP_HOST: ${PHP_HOST}
      PROJECT_DOMAIN: ${PROJECT_DOMAIN}
    ports:
      - ${WEB_HTTP_PORT}:80
      - ${WEB_HTTPS_PORT}:443
    volumes:
      - .:/var/www/web
    networks: 
      - drupal

  php:
    container_name: php_${PROJECT_NAME}
    build: 
      context: ./docker/php
      args:
        uname: ${DOCKER_USERNAME}
        uid: ${LOCAL_UID}
        gid: ${LOCAL_GID}
    ports: 
      - ${PHP_PORT}:9000
    volumes: 
      - .:/var/www/web
    networks: 
      - drupal

  mysql:
    container_name: mysql_${PROJECT_NAME}
    image: mariadb:10.7.1
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports: 
      - ${MYSQL_PORT}:3306
    volumes: 
      - ./docker/mysql:/var/lib/mysql
    networks: 
      - drupal

  redis:
    container_name: redis_${PROJECT_NAME}
    build: ./docker/redis
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - drupal

  node:
    container_name: node_${PROJECT_NAME}
    image: node:alpine3.14
    ports:
      - ${NODE_PORT}:3000
    volumes: 
      - .:/var/www/web
    tty: true

networks: 
  drupal:
